### ISSUE TITLE
Support for local LLM

### ISSUE THREAD

**Issue by punithrudrappa** [AurelienStebe/Gladdis#5]
Support local LLM using Ollama or llama.cpp

Many of these opensource projects provides APIs similar to OpenAI's APIs. Please provide an option to integrate them.

**Comment by AurelienStebe** [comment]
It was always part of the plan, but sorry it took so long. I'm picking the project back up. Releases should soon follow.

Version 0.6 is fresh out of the oven with local LLMs support (tested with Ollama & LocalAI) and image vision support, as a bonus.
